### ISSUE TITLE
Exception in interactive mode

### ISSUE THREAD

**Issue by perepelkin** [nikkollaii/parser#1]
```
/parser$ ~/local/jdk1.8.0_111/bin/java -jar Parser.jar
<Parser>: введите парамметры, для работы. Для запуска системы введите -s
<Pasres>: help
<Parser>: Для работы pasrer'а доступны следующие входные параметры:
<Parser>: -t  ...
<Parser>: -m  ...
<Parser>: -s  - запуск системы
<Parser>: <nameFileCM> ...
<Parser>: -o <nameFileOut> ...
<Parser>: введите парамметры, для работы. Для запуска системы введите -s
<Pasres>: -t cm.cm -o out.txt
<Parser>: введите парамметры, для работы. Для запуска системы введите -s
<Pasres>: -s
## Пример вычислительной модели
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1
        at computationalModel.line.CMLine.<init>(Unknown Source)
        at computationalModel.file.CMFile.readFile(Unknown Source)
        at parser.Parser.start(Unknown Source)
        at parser.Parser.main(Unknown Source)

```

**Comment by nikkollaii** [comment]
2 строка начинается не с символа '#' а с '\uFEFF' 65279

**Comment by nikkollaii** [comment]
Ошибка в составлении файла cm.cm
